language: python
python:
 - "3.6"
 - "3.7"
 - "3.8"
services:
  - postgresql
install:
    - pip install -r backend/requirements.txt
    - pip install -r test/requirements.txt
    - pip install -r scripts/importer/requirements.txt
script:
    - test/travis_script.sh
addons:
  postgresql: "10"
