language: python
python:
    - "3.5"
services:
    - docker
before_install:
    - test/travis_before_install.sh
install:
    - pip install -r backend/requirements.txt
script:
    - test/travis_script.sh
