language: python
python:
    - "3.5"
services:
    - docker
before_install:
    - test/travis_before_install.sh
install:
    - pip install -r backend/requirements.txt
    - pip install coverage coveralls
script:
    - test/travis_script.sh
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-client-10
