version: "3.2"
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile-backend
    depends_on:
      - db
    ports:
      - 4000:4000
    restart: on-failure
    volumes:
      - type: bind
        source: ./backend
        target: /code/backend
      - type: bind
        source: ./frontend
        target: /code/frontend
      - type: bind
        source: ./static
        target: /code/static
  db:
    restart: always
    image: postgres:10
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  rebuilder:
    build:
      context: ./
      dockerfile: Dockerfile-frontend-rebuilder
    volumes:
      - type: bind
        source: ./frontend
        target: /code/frontend
      - type: bind
        source: ./static
        target: /code/static
